#ifndef _FUNC_H_
#define _FUNC_H_

#include <stdio.h>
#define MAX_SIZE 2048

struct regs {
	unsigned short mem[MAX_SIZE];
	unsigned short comm_count;
	unsigned short comm_reg;
	unsigned short address_reg;
	unsigned short data_reg;
	unsigned int buffer_reg;
	unsigned short status_register;
	unsigned short accum;
	unsigned char c_bit;
	unsigned char n_bit;
	unsigned char z_bit;
	unsigned short mic_com_reg;
	unsigned short count_mic_com;
};


void func0(struct regs *myreg);
void func1(struct regs *myreg);
void func2(struct regs *myreg);
void func3(struct regs *myreg);
void func4(struct regs *myreg);
void func5(struct regs *myreg);
void func6(struct regs *myreg);
void func7(struct regs *myreg);
void func8(struct regs *myreg);
void func9(struct regs *myreg);
void func10(struct regs *myreg);
void func11(struct regs *myreg);
void func12(struct regs *myreg);
void func13(struct regs *myreg);
void func14(struct regs *myreg);
void func15(struct regs *myreg);
void func16(struct regs *myreg);
void func17(struct regs *myreg);
void func18(struct regs *myreg);
void func19(struct regs *myreg);
void func20(struct regs *myreg);
void func21(struct regs *myreg);
void func22(struct regs *myreg);
void func23(struct regs *myreg);
void func24(struct regs *myreg);
void func25(struct regs *myreg);
void func26(struct regs *myreg);
void func27(struct regs *myreg);
void func28(struct regs *myreg);
void func29(struct regs *myreg);
void func30(struct regs *myreg);
void func31(struct regs *myreg);
void func32(struct regs *myreg);
void func33(struct regs *myreg);
void func34(struct regs *myreg);
void func35(struct regs *myreg);
void func36(struct regs *myreg);
void func37(struct regs *myreg);
void func38(struct regs *myreg);
void func39(struct regs *myreg);
void func40(struct regs *myreg);
void func41(struct regs *myreg);
void func42(struct regs *myreg);
void func43(struct regs *myreg);
void func44(struct regs *myreg);
void func45(struct regs *myreg);
void func46(struct regs *myreg);
void func47(struct regs *myreg);
void func48(struct regs *myreg);
void func49(struct regs *myreg);
void func50(struct regs *myreg);
void func51(struct regs *myreg);
void func52(struct regs *myreg);
void func53(struct regs *myreg);
void func54(struct regs *myreg);
void func55(struct regs *myreg);
void func56(struct regs *myreg);
void func57(struct regs *myreg);
void func58(struct regs *myreg);
void func59(struct regs *myreg);
void func60(struct regs *myreg);
void func61(struct regs *myreg);
void func62(struct regs *myreg);
void func63(struct regs *myreg);
void func64(struct regs *myreg);
void func65(struct regs *myreg);
void func66(struct regs *myreg);
void func67(struct regs *myreg);
void func68(struct regs *myreg);
void func69(struct regs *myreg);
void func70(struct regs *myreg);
void func71(struct regs *myreg);
void func72(struct regs *myreg);
void func73(struct regs *myreg);
void func74(struct regs *myreg);
void func75(struct regs *myreg);
void func76(struct regs *myreg);
void func77(struct regs *myreg);
void func78(struct regs *myreg);
void func79(struct regs *myreg);
void func80(struct regs *myreg);
void func81(struct regs *myreg);
void func82(struct regs *myreg);
void func83(struct regs *myreg);
void func84(struct regs *myreg);
void func85(struct regs *myreg);
void func86(struct regs *myreg);
void func87(struct regs *myreg);
void func88(struct regs *myreg);
void func89(struct regs *myreg);
void func90(struct regs *myreg);
void func91(struct regs *myreg);
void func92(struct regs *myreg);
void func93(struct regs *myreg);
void func94(struct regs *myreg);
void func95(struct regs *myreg);
void func96(struct regs *myreg);
void func97(struct regs *myreg);
void func98(struct regs *myreg);
void func99(struct regs *myreg);
void func100(struct regs *myreg);
void func101(struct regs *myreg);
void func102(struct regs *myreg);
void func103(struct regs *myreg);
void func104(struct regs *myreg);
void func105(struct regs *myreg);
void func106(struct regs *myreg);
void func107(struct regs *myreg);
void func108(struct regs *myreg);
void func109(struct regs *myreg);
void func110(struct regs *myreg);
void func111(struct regs *myreg);
void func112(struct regs *myreg);
void func113(struct regs *myreg);
void func114(struct regs *myreg);
void func115(struct regs *myreg);
void func116(struct regs *myreg);
void func117(struct regs *myreg);
void func118(struct regs *myreg);
void func119(struct regs *myreg);
void func120(struct regs *myreg);
void func121(struct regs *myreg);
void func122(struct regs *myreg);
void func123(struct regs *myreg);
void func124(struct regs *myreg);
void func125(struct regs *myreg);
void func126(struct regs *myreg);
void func127(struct regs *myreg);
void func128(struct regs *myreg);
void func129(struct regs *myreg);
void func130(struct regs *myreg);
void func131(struct regs *myreg);
void func132(struct regs *myreg);
void func133(struct regs *myreg);
void func134(struct regs *myreg);
void func135(struct regs *myreg);
void func136(struct regs *myreg);

#endif
